esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: ${name_add_mac_suffix}
  project:
    name: ${project_name}
    version: ${project_version}
esp32:
  board: seeed_xiao_esp32s3
  flash_size: 8MB
  partitions: packages/presence-sensor-xiao-s3/partitions-8mb.csv
  framework:
    type: esp-idf
psram:
  mode: octal
  speed: 80MHz
logger:
  level: INFO
api:
  encryption: {}
wifi:
  output_power: 8.5dB
  
  # Fallback AP for initial setup
  ap:
    password: "psensor7777"
    ap_timeout: 0s

# Wi-Fi provisioning support
esp32_improv:
  authorizer: none
  status_indicator: user_led_output

# Home Assistant Bluetooth proxy
bluetooth_proxy:
  active: true

# mDNS device discovery
mdns:
  disabled: false
time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Seoul
i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
uart:
  id: uart_bus
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
output:
  - platform: gpio
    pin: GPIO21
    id: user_led_output
    inverted: true
light:
  - platform: binary
    id: status_led
    name: "Status LED"
    output: user_led_output
    entity_category: config
